name: Update README cards

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show=reviews,discussions_started,discussions_answered,prs_merged&include_all_commits=true&show_icons=true&theme=transparent&bg_color=00000000&hide_border=true
          path: profile/stats.svg
          #token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate lang card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&size_weight=0.5&count_weight=0.5&layout=compact&langs_count=10&hide=css,javascript,html&exclude_repo=Zonos&theme=transparent&hide_border=true
          path: profile/langs.svg
          #token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=dotfiles&theme=transparent&hide_border=true
          path: profile/pin.svg
          #token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
